In [1]:
import numpy as np
import pandas as pd
from tqdm import tqdm

In [2]:
train_data=pd.read_csv('Classification_train.csv')
test_data=pd.read_csv('Classification_test.csv')
X_train=train_data.drop("label",axis="columns").to_numpy()
y_train=train_data.iloc[:,0].to_numpy()
X_test=test_data.drop("ID",axis="columns").to_numpy()
y_test=test_data.iloc[:,0].to_numpy()

In [3]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [4]:
def LogisticRegression(X_train,y_train,learning_rate=0.01,epochs=1000):
    X_train=np.insert(X_train,0,1,axis=1)
    weights=np.random.rand(X_train.shape[1],len(np.unique(y_train)))
    for i in tqdm(range(epochs)):
        y_pred=sigmoid(np.dot(X_train,weights))
        weights += (learning_rate / X_train.shape[0]) * np.dot(X_train.T,(np.eye(len(np.unique(y_train)))[y_train] - y_pred))
    return weights

def predict(X_test, weights):
    X_test = np.insert(X_test, 0, 1, axis=1)
    y_pred = sigmoid(np.dot(X_test, weights))
    return y_pred


In [5]:
weights=LogisticRegression(X_train,y_train)

  0%|          | 1/1000 [00:02<33:40,  2.02s/it]C:\Users\Dell\AppData\Local\Temp\ipykernel_11808\1844366379.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-z))
100%|██████████| 1000/1000 [28:33<00:00,  1.71s/it]


In [6]:
prediction=predict(X_train,weights)
prediction2=predict(X_test,weights)

C:\Users\Dell\AppData\Local\Temp\ipykernel_11808\1844366379.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-z))


In [15]:
y_pred1=np.argmax(prediction2,axis=1)
print(y_pred1)
print(y_test)

[0 4 5 ... 0 8 1]
[15795   860  5390 ...   634 10057 13345]


In [17]:
y_pred = np.argmax(prediction, axis=1)
print(y_pred)
print(y_train)

[0 8 1 ... 9 3 5]
[0 8 1 ... 9 3 9]


In [10]:
def SSM(y_train):
    return np.sum((y_train-np.mean(y_train))**2)
def SSR(y_train,y_pred):
    return np.sum((y_train-y_pred)**2)
    
SSr=SSR(y_train,y_pred)
SSm=SSM(y_train)
r2_score=1-(SSr/SSm)
r2_score

0.9527796880732657

In [13]:
def SSM(y_train):
    return np.sum((y_train-np.mean(y_train))**2)
def SSR(y_train,y_pred):
    return np.sum((y_train-y_pred)**2)
    
SSr=SSR(y_test,y_pred1)
SSm=SSM(y_test)
r2_score=1-(SSr/SSm)
r2_score

-2.950409292084464